# Root log level and output appender.
log4j.rootLogger=INFO, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
# Console appender to stderr.
log4j.appender.console.target=System.err
# Log message layout.
log4j.appender.console.layout=org.apache.log4j.PatternLayout
# Timestamp, level, logger, message.
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
